In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
##sentences
sent=[ 'the glass of milk',
       'the glass of juice',
       'the cup of tea',
       'i am a good boy',
       'i am a good developper',
       'understand the meaning of words',
       'your videos are good'
]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'i am a good developper',
 'understand the meaning of words',
 'your videos are good']

In [5]:
##define the vocabulary size
voc_size=10000

In [6]:
###One Hot Representation for every word
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr


[[1438, 8440, 8618, 9186],
 [1438, 8440, 8618, 3832],
 [1438, 9903, 8618, 5307],
 [8489, 7143, 256, 2389, 5415],
 [8489, 7143, 256, 2389, 4973],
 [5219, 1438, 4278, 8618, 8508],
 [7738, 7816, 5484, 2389]]

In [7]:
## WOrd Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np


In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 1438, 8440, 8618, 9186],
       [   0,    0,    0,    0, 1438, 8440, 8618, 3832],
       [   0,    0,    0,    0, 1438, 9903, 8618, 5307],
       [   0,    0,    0, 8489, 7143,  256, 2389, 5415],
       [   0,    0,    0, 8489, 7143,  256, 2389, 4973],
       [   0,    0,    0, 5219, 1438, 4278, 8618, 8508],
       [   0,    0,    0,    0, 7738, 7816, 5484, 2389]])

In [10]:
##feature representation
dim=10


In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 192ms/step


array([[[-0.0325564 , -0.03302888,  0.02651915, -0.02593374,
         -0.04469371, -0.02736929, -0.0310058 , -0.04660219,
         -0.00728084, -0.0223251 ],
        [-0.0325564 , -0.03302888,  0.02651915, -0.02593374,
         -0.04469371, -0.02736929, -0.0310058 , -0.04660219,
         -0.00728084, -0.0223251 ],
        [-0.0325564 , -0.03302888,  0.02651915, -0.02593374,
         -0.04469371, -0.02736929, -0.0310058 , -0.04660219,
         -0.00728084, -0.0223251 ],
        [-0.0325564 , -0.03302888,  0.02651915, -0.02593374,
         -0.04469371, -0.02736929, -0.0310058 , -0.04660219,
         -0.00728084, -0.0223251 ],
        [-0.02448758, -0.02312161, -0.03728712, -0.01785462,
          0.03502036, -0.03813788,  0.0003837 , -0.02356796,
         -0.04833582,  0.00949731],
        [ 0.02894333, -0.01712822, -0.02740271, -0.04088189,
          0.01524837,  0.00114932, -0.04671918,  0.02503053,
          0.02495862, -0.04011575],
        [-0.014477  , -0.0069181 ,  0.02785242, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 1438, 8440, 8618, 9186])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 40ms/step


array([[-0.0325564 , -0.03302888,  0.02651915, -0.02593374, -0.04469371,
        -0.02736929, -0.0310058 , -0.04660219, -0.00728084, -0.0223251 ],
       [-0.0325564 , -0.03302888,  0.02651915, -0.02593374, -0.04469371,
        -0.02736929, -0.0310058 , -0.04660219, -0.00728084, -0.0223251 ],
       [-0.0325564 , -0.03302888,  0.02651915, -0.02593374, -0.04469371,
        -0.02736929, -0.0310058 , -0.04660219, -0.00728084, -0.0223251 ],
       [-0.0325564 , -0.03302888,  0.02651915, -0.02593374, -0.04469371,
        -0.02736929, -0.0310058 , -0.04660219, -0.00728084, -0.0223251 ],
       [-0.02448758, -0.02312161, -0.03728712, -0.01785462,  0.03502036,
        -0.03813788,  0.0003837 , -0.02356796, -0.04833582,  0.00949731],
       [ 0.02894333, -0.01712822, -0.02740271, -0.04088189,  0.01524837,
         0.00114932, -0.04671918,  0.02503053,  0.02495862, -0.04011575],
       [-0.014477  , -0.0069181 ,  0.02785242, -0.00885845,  0.03932737,
        -0.03913014, -0.00395142,  0.005705  